import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../../", import.meta.url));
const outputs = {
  tauri: "crates/tauri-plugin-webdesktopmcp/src/bootstrap.js",
  wails: "go/webdesktopmcp/js/bootstrap.js",
};
for (const [adapter, output] of Object.entries(outputs)) {
  const result = await build({
    absWorkingDir: root,
    entryPoints: [`packages/core/src/adapters/${adapter}.ts`],
    alias: { "@webdesktopmcp/protocol": path.join(root, "packages/protocol/src/index.ts") },
    bundle: true, format: "iife", platform: "browser", target: "es2020",
    minify: true, write: false, legalComments: "none",
    banner: { js: "// Generated by packages/electron/build-native.mjs; edit packages/core/src/adapters instead." },
  });
  const source = result.outputFiles[0].text;
  const target = path.join(root, output);
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== source) throw new Error(`${output} is stale; run node packages/electron/build-native.mjs`);
  } else writeFileSync(target, source);
}
